# Generated by Django 5.0.3 on 2024-03-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_lectures", "0002_group_subject_homework_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="group",
            new_name="position",
        ),
        migrations.CreateModel(
            name="Employee_and_group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_lectures.employee",
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_lectures.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token_value", models.CharField(max_length=20)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_lectures.group",
                    ),
                ),
            ],
        ),
    ]
