# Generated by Django 5.0.3 on 2024-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_lectures",
            "0003_rename_group_employee_position_employee_and_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="vkID",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
