# Generated by Django 5.0.3 on 2024-03-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_lectures", "0005_employee_vkid_student_vkid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject_and_group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_lectures.group",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_lectures.subject",
                    ),
                ),
            ],
        ),
    ]
