# Generated by Django 5.0.3 on 2024-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_lectures", "0007_subject_and_group_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_and_group",
            name="group_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject_and_group",
            name="subject_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
