# Generated by Django 5.0.3 on 2024-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_lectures", "0008_subject_and_group_group_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="vkID",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
